///$tab Start
Gitoqlik
Gitoqlik is on the active testing stage.
Your feedback could make product better. Please, take our 1-minutes survey
Found Qlik application "1.2 Incremental load orders(1)"
// Context
Set vContext = 'DEV';
//Set vContext = 'PROD';

// Load *.qvs files
$(Must_Include=lib://FC_S_$(vContext)/sub_log.qvs);
$(Must_Include=lib://FC_S_$(vContext)/sub_store.qvs);

// Start logging
Call Log('Start');

// Log context
Call Log('$(vContext)');